// AUTO-GENERATED by 13a-rules-db's scripts/generate-archmage-setup.mjs
// (1e) from vtt-scripts/*.js and data/1e/classes/*.yaml — do not
// hand-edit: change the vtt-scripts source or the data, then re-run the
// generator. See docs/VTT-SCRIPTS.md.
(() => {
const DA_DATA = {
  "classPackName": "classes",
  "classes": [
    {
      "id": "abomination",
      "name": "Abomination",
      "baseStats": {
        "hp": 7,
        "ac_lgt": 13,
        "ac_hvy": 15,
        "ac_hvy_pen": -5,
        "shld_pen": -2,
        "pd": 11,
        "md": 10,
        "rec_die": 10,
        "wpn_1h": 8,
        "wpn_2h": 10,
        "wpn_2h_pen": -1,
        "wpn_rngd": 4,
        "skilled_warrior": true
      },
      "keyModifiers": {
        "barbarian": [
          "str",
          "con"
        ],
        "bard": [
          "str",
          "cha"
        ],
        "chaosmage": [
          "str",
          "cha"
        ],
        "cleric": [
          "str",
          "wis"
        ],
        "commander": [
          "str",
          "cha"
        ],
        "druid": [
          "str",
          "wis"
        ],
        "fateweaver": [
          "str",
          "wis"
        ],
        "fighter": [
          "str",
          "con"
        ],
        "monk": [
          "str",
          "dex"
        ],
        "necromancer": [
          "str",
          "int"
        ],
        "occultist": [
          "str",
          "int"
        ],
        "paladin": [
          "str",
          "cha"
        ],
        "psion": [
          "str",
          "int"
        ],
        "ranger": [
          "str",
          "dex"
        ],
        "rogue": [
          "str",
          "dex"
        ],
        "savage": [
          "str",
          "con"
        ],
        "sorcerer": [
          "str",
          "cha"
        ],
        "swordmage": [
          "str",
          "int"
        ],
        "warlock": [
          "str",
          "cha"
        ],
        "wizard": [
          "str",
          "int"
        ]
      },
      "customResources": null
    },
    {
      "id": "darkalleysdruid",
      "name": "Dark Alleys Druid",
      "baseStats": {
        "hp": 6,
        "ac_lgt": 10,
        "ac_hvy": 14,
        "ac_hvy_pen": -2,
        "shld_pen": -2,
        "pd": 11,
        "md": 11,
        "rec_die": 6,
        "wpn_1h": 6,
        "wpn_2h": 8,
        "wpn_2h_pen": 0,
        "wpn_rngd": 6,
        "skilled_warrior": false
      },
      "keyModifiers": {
        "abomination": [
          "str",
          "wis"
        ],
        "barbarian": [
          "str",
          "wis"
        ],
        "bard": [
          "wis",
          "cha"
        ],
        "chaosmage": [
          "wis",
          "cha"
        ],
        "cleric": [
          "str",
          "wis"
        ],
        "commander": [
          "wis",
          "cha"
        ],
        "fateweaver": [
          "str",
          "wis"
        ],
        "fighter": [
          "str",
          "wis"
        ],
        "monk": [
          "dex",
          "wis"
        ],
        "necromancer": [
          "int",
          "wis"
        ],
        "occultist": [
          "int",
          "wis"
        ],
        "paladin": [
          "str",
          "wis"
        ],
        "psion": [
          "int",
          "wis"
        ],
        "ranger": [
          "dex",
          "wis"
        ],
        "rogue": [
          "dex",
          "wis"
        ],
        "savage": [
          "str",
          "wis"
        ],
        "sorcerer": [
          "wis",
          "cha"
        ],
        "swordmage": [
          "int",
          "wis"
        ],
        "warlock": [
          "wis",
          "cha"
        ],
        "wizard": [
          "int",
          "wis"
        ]
      },
      "customResources": null
    },
    {
      "id": "fateweaver",
      "name": "Fateweaver",
      "baseStats": {
        "hp": 5,
        "ac_lgt": 11,
        "ac_hvy": 12,
        "ac_hvy_pen": -2,
        "shld_pen": -1,
        "pd": 10,
        "md": 12,
        "rec_die": 6,
        "wpn_1h": 6,
        "wpn_2h": 10,
        "wpn_2h_pen": -5,
        "wpn_rngd": 6,
        "skilled_warrior": false
      },
      "keyModifiers": {
        "abomination": [
          "str",
          "wis"
        ],
        "barbarian": [
          "str",
          "wis"
        ],
        "bard": [
          "wis",
          "cha"
        ],
        "chaosmage": [
          "wis",
          "cha"
        ],
        "cleric": [
          "wis",
          "cha"
        ],
        "commander": [
          "wis",
          "cha"
        ],
        "druid": [
          "str",
          "wis"
        ],
        "fighter": [
          "str",
          "wis"
        ],
        "monk": [
          "dex",
          "wis"
        ],
        "necromancer": [
          "int",
          "cha"
        ],
        "occultist": [
          "int",
          "wis"
        ],
        "paladin": [
          "str",
          "wis"
        ],
        "psion": [
          "int",
          "wis"
        ],
        "ranger": [
          "str",
          "wis"
        ],
        "rogue": [
          "dex",
          "cha"
        ],
        "savage": [
          "str",
          "wis"
        ],
        "sorcerer": [
          "wis",
          "cha"
        ],
        "swordmage": [
          "int",
          "wis"
        ],
        "warlock": [
          "int",
          "cha"
        ],
        "wizard": [
          "int",
          "wis"
        ]
      },
      "customResources": null
    },
    {
      "id": "gunslinger",
      "name": "Gunslinger",
      "baseStats": {
        "hp": 7,
        "ac_lgt": 13,
        "ac_hvy": 14,
        "ac_hvy_pen": -2,
        "shld_pen": -2,
        "pd": 11,
        "md": 10,
        "rec_die": 8,
        "wpn_1h": 8,
        "wpn_2h": 10,
        "wpn_2h_pen": -2,
        "wpn_rngd": 8,
        "skilled_warrior": false
      },
      "keyModifiers": {
        "abomination": [
          "str",
          "dex"
        ],
        "barbarian": [
          "str",
          "dex"
        ],
        "bard": [
          "dex",
          "cha"
        ],
        "chaosmage": [
          "dex",
          "cha"
        ],
        "cleric": [
          "str",
          "wis"
        ],
        "commander": [
          "str",
          "cha"
        ],
        "druid": [
          "dex",
          "wis"
        ],
        "fateweaver": [
          "str",
          "wis"
        ],
        "fighter": [
          "str",
          "dex"
        ],
        "monk": [
          "str",
          "dex"
        ],
        "necromancer": [
          "dex",
          "int"
        ],
        "occultist": [
          "dex",
          "int"
        ],
        "paladin": [
          "str",
          "dex"
        ],
        "psion": [
          "dex",
          "int"
        ],
        "ranger": [
          "dex",
          "wis"
        ],
        "rogue": [
          "str",
          "dex"
        ],
        "savage": [
          "str",
          "dex"
        ],
        "sorcerer": [
          "dex",
          "cha"
        ],
        "swordmage": [
          "dex",
          "int"
        ],
        "warlock": [
          "dex",
          "cha"
        ],
        "wizard": [
          "dex",
          "int"
        ]
      },
      "customResources": [
        [
          "Grit",
          "quick"
        ]
      ]
    },
    {
      "id": "psion",
      "name": "Psion",
      "baseStats": {
        "hp": 6,
        "ac_lgt": 10,
        "ac_hvy": 11,
        "ac_hvy_pen": -2,
        "shld_pen": 0,
        "pd": 10,
        "md": 12,
        "rec_die": 6,
        "wpn_1h": 6,
        "wpn_2h": 10,
        "wpn_2h_pen": -3,
        "wpn_rngd": 6,
        "skilled_warrior": false
      },
      "keyModifiers": {
        "abomination": [
          "str",
          "int"
        ],
        "barbarian": [
          "str",
          "int"
        ],
        "bard": [
          "int",
          "cha"
        ],
        "chaosmage": [
          "int",
          "cha"
        ],
        "cleric": [
          "int",
          "wis"
        ],
        "commander": [
          "int",
          "cha"
        ],
        "druid": [
          "int",
          "wis"
        ],
        "fateweaver": [
          "int",
          "wis"
        ],
        "fighter": [
          "str",
          "int"
        ],
        "monk": [
          "dex",
          "int"
        ],
        "necromancer": [
          "int",
          "cha"
        ],
        "occultist": [
          "int",
          "cha"
        ],
        "paladin": [
          "str",
          "int"
        ],
        "ranger": [
          "dex",
          "int"
        ],
        "rogue": [
          "dex",
          "int"
        ],
        "savage": [
          "str",
          "int"
        ],
        "sorcerer": [
          "int",
          "cha"
        ],
        "swordmage": [
          "con",
          "int"
        ],
        "warlock": [
          "int",
          "cha"
        ],
        "wizard": [
          "con",
          "int"
        ]
      },
      "customResources": [
        [
          "PP",
          "quick"
        ]
      ]
    },
    {
      "id": "ranger",
      "name": "Ranger",
      "baseStats": null,
      "keyModifiers": null,
      "customResources": [
        [
          "Charges",
          "full"
        ]
      ]
    },
    {
      "id": "savage",
      "name": "Savage",
      "baseStats": {
        "hp": 8,
        "ac_lgt": 12,
        "ac_hvy": 13,
        "ac_hvy_pen": -2,
        "shld_pen": 0,
        "pd": 11,
        "md": 10,
        "rec_die": 10,
        "wpn_1h": 8,
        "wpn_2h": 10,
        "wpn_2h_pen": 0,
        "wpn_rngd": 8,
        "skilled_warrior": true
      },
      "keyModifiers": {
        "abomination": [
          "str",
          "con"
        ],
        "barbarian": [
          "str",
          "con"
        ],
        "bard": [
          "str",
          "cha"
        ],
        "chaosmage": [
          "str",
          "cha"
        ],
        "cleric": [
          "str",
          "wis"
        ],
        "commander": [
          "str",
          "cha"
        ],
        "druid": [
          "str",
          "wis"
        ],
        "fateweaver": [
          "str",
          "wis"
        ],
        "fighter": [
          "str",
          "con"
        ],
        "monk": [
          "str",
          "dex"
        ],
        "necromancer": [
          "str",
          "int"
        ],
        "occultist": [
          "str",
          "int"
        ],
        "paladin": [
          "str",
          "cha"
        ],
        "psion": [
          "str",
          "int"
        ],
        "ranger": [
          "str",
          "dex"
        ],
        "rogue": [
          "str",
          "dex"
        ],
        "sorcerer": [
          "str",
          "cha"
        ],
        "swordmage": [
          "str",
          "int"
        ],
        "warlock": [
          "str",
          "cha"
        ],
        "wizard": [
          "str",
          "int"
        ]
      },
      "customResources": [
        [
          "Frenzy",
          "quickreset"
        ],
        [
          "Frenzydiesize",
          "none"
        ]
      ]
    },
    {
      "id": "swordmage",
      "name": "Swordmage",
      "baseStats": {
        "hp": 7,
        "ac_lgt": 15,
        "ac_hvy": 15,
        "ac_hvy_pen": -2,
        "shld_pen": 0,
        "pd": 10,
        "md": 12,
        "rec_die": 8,
        "wpn_1h": 8,
        "wpn_2h": 10,
        "wpn_2h_pen": 0,
        "wpn_rngd": 8,
        "skilled_warrior": true
      },
      "keyModifiers": {
        "abomination": [
          "str",
          "int"
        ],
        "barbarian": [
          "str",
          "int"
        ],
        "bard": [
          "int",
          "cha"
        ],
        "chaosmage": [
          "int",
          "cha"
        ],
        "cleric": [
          "int",
          "wis"
        ],
        "commander": [
          "int",
          "cha"
        ],
        "druid": [
          "int",
          "wis"
        ],
        "fateweaver": [
          "int",
          "wis"
        ],
        "fighter": [
          "str",
          "int"
        ],
        "monk": [
          "dex",
          "int"
        ],
        "necromancer": [
          "int",
          "cha"
        ],
        "occultist": [
          "int",
          "cha"
        ],
        "paladin": [
          "str",
          "int"
        ],
        "psion": [
          "con",
          "int"
        ],
        "ranger": [
          "dex",
          "int"
        ],
        "rogue": [
          "dex",
          "int"
        ],
        "savage": [
          "str",
          "int"
        ],
        "sorcerer": [
          "int",
          "cha"
        ],
        "warlock": [
          "int",
          "cha"
        ],
        "wizard": [
          "con",
          "int"
        ]
      },
      "customResources": null
    },
    {
      "id": "warlock",
      "name": "Warlock",
      "baseStats": {
        "hp": 6,
        "ac_lgt": 11,
        "ac_hvy": 12,
        "ac_hvy_pen": -2,
        "shld_pen": -2,
        "pd": 11,
        "md": 11,
        "rec_die": 6,
        "wpn_1h": 6,
        "wpn_2h": 10,
        "wpn_2h_pen": -2,
        "wpn_rngd": 8,
        "skilled_warrior": false
      },
      "keyModifiers": {
        "abomination": [
          "str",
          "cha"
        ],
        "barbarian": [
          "str",
          "cha"
        ],
        "bard": [
          "dex",
          "cha"
        ],
        "chaosmage": [
          "con",
          "cha"
        ],
        "cleric": [
          "wis",
          "cha"
        ],
        "commander": [
          "str",
          "cha"
        ],
        "druid": [
          "wis",
          "cha"
        ],
        "fateweaver": [
          "int",
          "cha"
        ],
        "fighter": [
          "str",
          "cha"
        ],
        "monk": [
          "dex",
          "cha"
        ],
        "necromancer": [
          "int",
          "cha"
        ],
        "occultist": [
          "int",
          "cha"
        ],
        "paladin": [
          "str",
          "cha"
        ],
        "psion": [
          "int",
          "cha"
        ],
        "ranger": [
          "dex",
          "cha"
        ],
        "rogue": [
          "dex",
          "cha"
        ],
        "savage": [
          "str",
          "cha"
        ],
        "sorcerer": [
          "con",
          "cha"
        ],
        "swordmage": [
          "int",
          "cha"
        ],
        "wizard": [
          "int",
          "cha"
        ]
      },
      "customResources": null
    }
  ],
  "coreGroups": {
    "wizard": {
      "shield": "Abjuration",
      "teleport shield": "Abjuration",
      "invisibility purge": "Abjuration",
      "acid arrow": "Conjuration",
      "summon wizard's earth elemental": "Conjuration",
      "crescendo": "Conjuration",
      "summon imp": "Conjuration",
      "dimension door": "Conjuration",
      "summon frenzy demon": "Conjuration",
      "summon laughing demon": "Conjuration",
      "teleport": "Conjuration",
      "charm person": "Enchantment",
      "confusion": "Enchantment",
      "hold monster": "Enchantment",
      "rebuke": "Enchantment",
      "sleep": "Enchantment",
      "denial": "Enchantment",
      "magic missile": "Evocation",
      "ray of frost": "Evocation",
      "shocking grasp": "Evocation",
      "force salvo": "Evocation",
      "lightning bolt": "Evocation",
      "fireball": "Evocation",
      "meteor swarm": "Evocation",
      "blur": "Illusion",
      "color spray": "Illusion",
      "invisibility": "Illusion",
      "blink": "Transmutation",
      "flight": "Transmutation",
      "haste": "Transmutation",
      "overcome resistance": "Transmutation",
      "transfer enchantment": "Transmutation",
      "disintegrate": "Transmutation"
    }
  },
  "importExtras": {
    "powers": {
      "druid": [
        {
          "name": "animal-companion-dark-alleys"
        }
      ],
      "darkalleysdruid": [
        {
          "name": "animal-companion-dark-alleys"
        },
        {
          "id": "archmage.animal-companion"
        },
        {
          "id": "archmage.druid",
          "only": [
            "Divine Implements",
            "Druidic Summoning",
            "Melee Attack: Strength or Speed",
            "Wilderness Survival",
            "Bear Aspect",
            "Behemoth Aspect",
            "Mantis Aspect",
            "Leopard Aspect",
            "Owlbear Aspect",
            "Tiger Aspect",
            "Wolverine Aspect",
            "Air & Fire",
            "Barkskin",
            "Call Lightning",
            "Cone of Cold",
            "Devastation",
            "Entangle",
            "Frost Touch (Terrain Feat Spell)",
            "Fungal Ambuscade",
            "Harmony",
            "Heat Metal",
            "How Things End",
            "Ice Shield",
            "Icicle",
            "Inevitable Collapse",
            "Koru Teleport",
            "Plantwalk",
            "Poison Thorns (Terrain Feat Spell)",
            "Purification Chant",
            "Rain of Acorns (Terrain Feat Spell)",
            "Reclamation",
            "Ruination (Terrain Feat Spell)",
            "Rumble",
            "Spark (Terrain Feat Spell)",
            "Spider Climb",
            "Spikestones",
            "Stomp!",
            "Stoneskin",
            "Sunbeams (Terrain Feat Spell)",
            "The Big Muddy",
            "The Koru Shrugs",
            "Ways of the Dark (Terrain Feat Spell)",
            "Whoomph (Terrain Feat Spell)",
            "Ancestral Guidance",
            "Greenmantle",
            "Invoke the Storm",
            "Nature’s Fury",
            "Red Claw",
            "Resilience",
            "Shillelagh",
            "Spirits of the Land",
            "Strength of Earth",
            "Warrior’s Blessing",
            "Wild Harmony"
          ]
        },
        {
          "name": "druid",
          "except": [
            "Terrain Caster: Desert, Wasteland",
            "Terrain Caster: Hellhole, Abyss",
            "Terrain Caster: Ocean, Island",
            "Terrain Caster: Volcano"
          ]
        }
      ],
      "ranger": [
        {
          "name": "animal-companion-dark-alleys"
        }
      ]
    },
    "companionTraits": [
      {
        "actorPack": "archmage.animal-companions",
        "traitPack": {
          "name": "animal-companion-dark-alleys"
        }
      }
    ]
  },
  "sceneTerrains": [
    "Cave, Dungeon, Underworld",
    "Desert, Wasteland",
    "Forest, Woods",
    "Hellhole, Abyss",
    "Ice, Tundra, Deep Snow",
    "Koru Behemoth",
    "Mountains",
    "Ocean, Island",
    "Plains, Overworld",
    "Ruins",
    "Swamp, Lake, River",
    "Volcano"
  ],
  "races": [
    {
      "id": "firesoul",
      "name": "Firesoul"
    },
    {
      "id": "halfogre",
      "name": "Half-Ogre"
    },
    {
      "id": "leomar",
      "name": "Leomar"
    },
    {
      "id": "nyama",
      "name": "Nyama"
    },
    {
      "id": "orc",
      "name": "Orc"
    },
    {
      "id": "pixie",
      "name": "Pixie"
    },
    {
      "id": "ratkin",
      "name": "Ratkin"
    },
    {
      "id": "rocksoul",
      "name": "Rocksoul"
    },
    {
      "id": "shadowborn",
      "name": "Shadowborn"
    },
    {
      "id": "starchild",
      "name": "Star Child"
    },
    {
      "id": "stormsoul",
      "name": "Stormsoul"
    },
    {
      "id": "vorhai",
      "name": "Vorhai"
    },
    {
      "id": "greyskin",
      "name": "Greyskin"
    },
    {
      "id": "watersoul",
      "name": "Watersoul"
    }
  ],
  "flagScope": "13a-rules-db"
};

// ---- vtt-scripts/register-classes.js ----
// Registers this module's classes with the archmage system at `ready`, so
// classes outside archmage's hardcoded class list are recognised (Import
// Powers class detection, base stats, key modifiers, class resources) — the
// same technique the dark-pacts-13th-age (2e) reference module uses.
//
// Runs inside Foundry, as part of the module's scripts/setup.js (see
// docs/VTT-SCRIPTS.md). Reads DA_DATA, written by
// scripts/generate-archmage-setup.mjs from data/<edition>/classes/*.yaml:
//   DA_DATA.classPackName — the module's class-journal pack ("classes" /
//     "classes-2e"). Without it in CONFIG.ARCHMAGE.classPacks, Import Powers
//     never shows this module's class journals (level table, etc.).
//   DA_DATA.classes — one record per class file with an
//     `archmage_class_config` block: { id (archmage-style, hyphens
//     stripped), name, baseStats (null = only resources are registered, for
//     a class archmage already knows), keyModifiers ({ otherClassId:
//     [ability, ability] }, written from this class's side), customResources }.
//
// keyModifiers pairs are written from every class's own perspective (both
// directions), not archmage's own base-game "alphabetical lower triangle,
// store once" convention — simpler and harmless, since the registration order
// here can't be assumed to match core's.
Hooks.on("ready", function () {
  CONFIG.ARCHMAGE.classPacks ??= [];
  if (!CONFIG.ARCHMAGE.classPacks.includes(DA_DATA.classPackName)) {
    CONFIG.ARCHMAGE.classPacks.push(DA_DATA.classPackName);
  }

  for (const cls of DA_DATA.classes) {
    if (cls.baseStats) {
      console.log(`${cls.name} (13th Age) class injecting data into the system...`);
      CONFIG.ARCHMAGE.classList[cls.id] = cls.name;
      CONFIG.ARCHMAGE.classes[cls.id] = cls.baseStats;
      if (cls.keyModifiers) {
        CONFIG.ARCHMAGE.keyModifiers[cls.id] ??= {};
        for (const [other, pair] of Object.entries(cls.keyModifiers)) {
          CONFIG.ARCHMAGE.keyModifiers[cls.id][other] = pair;
        }
      }
    }
    if (cls.customResources) {
      CONFIG.ARCHMAGE.classResources[cls.id] = cls.customResources;
    }
    if (cls.baseStats) console.log(`${cls.name} (13th Age) class loaded successfully.`);
  }
});

// ---- vtt-scripts/register-races.js ----
// Registers this module's races with the archmage system at `ready`, so
// Import Powers offers their racial powers and feats. archmage already loads
// every installed pack named "races" (or "kin-powers-2e" with its
// secondEdition setting on) — scripts/export-races.mjs gives ours that name —
// but it only matches a character's race text against the names in
// CONFIG.ARCHMAGE.raceList (archmage-prepopulate.js getCompendiums), so a race
// missing from that list never finds its powers, whatever pack they're in.
//
// Runs inside Foundry, as part of the module's scripts/setup.js (see
// docs/VTT-SCRIPTS.md). Reads DA_DATA.races, written by
// scripts/generate-archmage-setup.mjs from data/<edition>/races/*.yaml:
//   [{ id (archmage-style, separators stripped), name (display name) }]
// A race printed under two names ("Vorhai / Greyskin") has one record per
// name. archmage localizes raceList's values at `init`, so plain display
// names added at `ready` are already in the form it matches against.
Hooks.on("ready", function () {
  if (!DA_DATA.races?.length) return;
  CONFIG.ARCHMAGE.raceList ??= {};
  for (const race of DA_DATA.races) {
    CONFIG.ARCHMAGE.raceList[race.id] ??= race.name;
  }
  console.log(`Dark Alleys: ${DA_DATA.races.length} race name(s) registered for Import Powers.`);
});

// ---- vtt-scripts/core-groups.js ----
// Gives core (archmage) powers this module's own Foundry groups when they're
// added to an actor — e.g. core wizard spells join our school groups
// ("Magic Missile" -> "Evocation"), so the character sheet's
// "Group by: Custom Groups" view files them together with our spells.
//
// archmage's own packs are never edited (they're locked, and replaced on
// every system update). The sheet reads the group of the actor's own copy,
// so that copy gets the group when it's created, and only if it has none.
//
// Runs inside Foundry, as part of the module's scripts/setup.js (see
// docs/VTT-SCRIPTS.md). Reads DA_DATA.coreGroups, written by
// scripts/generate-archmage-setup.mjs from the class files' spell tables:
//   { <archmage pack name, e.g. "wizard">: { <normalized core power name>: <group> } }
// (docs/DATA-FORMAT.md "Core Items in our groups").

// Core Item id -> group, filled at `ready` from the installed core packs, so
// nothing depends on a particular archmage version's ids.
const coreGroupById = new Map();

Hooks.once("ready", async function () {
  const norm = (name) => name.replace(/[’']/g, "'").replace(/\s+/g, " ").trim().toLowerCase();
  for (const [packName, groups] of Object.entries(DA_DATA.coreGroups)) {
    const pack = game.packs.get(`archmage.${packName}`);
    if (!pack) continue;
    for (const entry of await pack.getIndex()) {
      const group = groups[norm(entry.name)];
      if (group) coreGroupById.set(entry._id, group);
    }
  }
  if (coreGroupById.size) {
    console.log(`Dark Alleys: ${coreGroupById.size} core power(s) get a custom group when added to an actor.`);
  }
});

// Both ways a core power reaches an actor are recognised by the core Item's
// id: Import Powers creates the Item from a plain copy of the pack document,
// so the creation data still carries the pack document's own `_id`; a drag
// from the compendium records `_stats.compendiumSource`
// ("Compendium.archmage.<pack>.Item.<id>").
Hooks.on("preCreateItem", function (item, data) {
  if (item.type !== "power" || !item.parent || item.system.group?.value) return;
  const source = item._stats?.compendiumSource ?? "";
  const fromSource = /^Compendium\.archmage\.[^.]+\.Item\.([^.]+)$/.exec(source)?.[1];
  const group = coreGroupById.get(fromSource ?? data?._id);
  if (group) item.updateSource({ "system.group.value": group });
});

// ---- vtt-scripts/import-extras.js ----
// Wires extra compendium content into archmage's own flows, the way archmage
// hardcodes it for its core classes (docs/ANIMAL-COMPANIONS.md):
//
// 1. Import Powers: archmage adds its "Animal Companion" pack to the power
//    list of the core ranger and druid only. This adds configured packs'
//    power Items to other classes too — e.g. core's companion talent and
//    spells for the Dark Alleys Druid, and our companion spell expansion for
//    the core Druid and the Dark Alleys Druid.
// 2. Companion actors: when an actor from a configured Actor pack (core's
//    "Animal Companion (N)" actors) is created in a world, our trait Items
//    (e.g. new animal types) are added to it, next to core's own choices.
//
// Runs inside Foundry, as part of the module's scripts/setup.js (see
// docs/VTT-SCRIPTS.md). Reads DA_DATA.importExtras, written by
// scripts/generate-archmage-setup.mjs from the class files' `foundry_import`
// blocks:
//   powers: { <archmage-style class id, e.g. "darkalleysdruid">: [<pack ref>] }
//   companionTraits: [{ actorPack: "<full Actor pack id>", traitPack: <pack ref> }]
// A pack ref is { id: "archmage.animal-companion" } for another package's
// pack, or { name: "animal-companion-dark-alleys" } for one of this module's
// own (looked up by name, so setup.js doesn't depend on the module's id).
// A ref may also carry `only: [Item names]` (just those Items) or `except:
// [Item names]` (all but those), matched ignoring case; a name in `only` that
// the pack doesn't have is reported in the console and to the GM, so a rename
// in the source pack can't silently drop e.g. a class's basic attacks.

const findPack = (ref) =>
  ref.id
    ? game.packs.get(ref.id)
    : game.packs.find((p) => p.metadata.packageType === "module" && p.metadata.name === ref.name);

// [{ actorPack, actorIds: Set of that pack's actor ids, traits: [trait Item data] }]
const companionTraitSets = [];

Hooks.once("ready", async function () {
  const extras = DA_DATA.importExtras;
  await wrapImportPowers(extras.powers);
  for (const { actorPack, traitPack } of extras.companionTraits) {
    const actors = game.packs.get(actorPack);
    const traits = findPack(traitPack);
    if (!actors || !traits) continue;
    companionTraitSets.push({
      actorPack,
      actorIds: new Set((await actors.getIndex()).map((e) => e._id)),
      traits: (await traits.getDocuments())
        .filter((d) => d.type === "trait")
        .map((d) => {
          const data = d.toObject();
          delete data._id;
          return data;
        }),
    });
  }
});

// archmage doesn't expose its Import Powers loader, but ships its code
// unbundled, so importing archmage-prepopulate.js relative to the system's own
// module script URL returns the very module instance archmage uses; wrapping
// the prototype method changes what every Import Powers dialog shows.
// Verified live 2026-09-25 (archmage 1.41 on Forge, script served from the
// Forge CDN).
const reported = new Set();

// Applies a ref's `only` / `except` name filter to a pack's power Items.
function selectItems(ref, pack, docs) {
  const same = (a, b) => a.toLowerCase() === b.toLowerCase();
  if (ref.only) {
    const missing = ref.only.filter((n) => !docs.some((d) => same(d.name, n)));
    for (const name of missing) {
      const key = `${pack.collection}:${name}`;
      if (reported.has(key)) continue;
      reported.add(key);
      const msg = `Dark Alleys: "${name}" is not in ${pack.collection}; Import Powers can't offer it.`;
      console.warn(msg);
      if (game.user.isGM) ui.notifications.warn(msg);
    }
    return docs.filter((d) => ref.only.some((n) => same(d.name, n)));
  }
  if (ref.except) return docs.filter((d) => !ref.except.some((n) => same(d.name, n)));
  return docs;
}

async function wrapImportPowers(powers) {
  const systemScript = [...document.querySelectorAll('script[type="module"][src]')]
    .map((s) => s.src)
    .find((src) => /\/systems\/archmage\/(.+\/)?module\/archmage\.js(\?|$)/.test(src));
  if (!systemScript) {
    console.warn("Dark Alleys: archmage's module script not found; Import Powers extras disabled.");
    return;
  }
  const { ArchmagePrepopulate } = await import(new URL("setup/archmage-prepopulate.js", systemScript).href);
  const proto = ArchmagePrepopulate?.prototype;
  if (typeof proto?.getCompendiums !== "function") {
    console.warn("Dark Alleys: archmage's getCompendiums not found; Import Powers extras disabled.");
    return;
  }
  const original = proto.getCompendiums;
  proto.getCompendiums = async function (classes = [], race = "") {
    const content = await original.call(this, classes, race);
    for (const [cls, refs] of Object.entries(powers)) {
      if (!classes.includes(cls) || !content?.[cls]) continue;
      for (const ref of refs) {
        const pack = findPack(ref);
        if (!pack) continue;
        const docs = selectItems(ref, pack, (await pack.getDocuments()).filter((d) => d.type === "power"));
        content[cls].content = docs.concat(content[cls].content);
      }
    }
    hideGrantedChildren(content);
    return content;
  };
  if (Object.keys(powers).length) console.log(`Dark Alleys: Import Powers extras for ${Object.keys(powers).join(", ")}.`);
}

// Child entries (docs/DATA-FORMAT.md "granted"): a child the parent adds by
// itself is hidden from the dialog, but only while its parent is listed in
// the same class group, so a broken link can never make a power unreachable.
function hideGrantedChildren(content) {
  const scope = DA_DATA.flagScope;
  for (const group of Object.values(content ?? {})) {
    if (!Array.isArray(group?.content)) continue;
    const docId = (d) => d.id ?? d._id;
    const listedGrants = new Set(group.content.flatMap((d) => (d.flags?.[scope]?.grants ?? []).map((g) => g.id)));
    group.content = group.content.filter((d) => !(d.flags?.[scope]?.autoGranted && listedGrants.has(docId(d))));
  }
}

// A dragged or imported compendium actor records `_stats.compendiumSource`
// ("Compendium.<pack id>.Actor.<id>"); the pack's own `_id` in the creation
// data is the fallback. Traits the actor already has (by name) are skipped,
// so duplicating a companion doesn't add them twice.
Hooks.on("preCreateActor", function (actor, data) {
  const source = actor._stats?.compendiumSource ?? "";
  for (const { actorPack, actorIds, traits } of companionTraitSets) {
    if (!source.startsWith(`Compendium.${actorPack}.Actor.`) && !actorIds.has(data?._id)) continue;
    const have = new Set(actor.items.map((i) => i.name));
    const add = traits.filter((t) => !have.has(t.name));
    if (add.length) actor.updateSource({ items: [...actor._source.items, ...add] });
  }
});

// ---- vtt-scripts/scene-terrains.js ----
// Adds the terrains this module's Druid content introduces (Desert/Wasteland,
// Hellhole/Abyss, Ocean/Island, Volcano) to archmage's scene terrain selector, the
// "Terrains Present" list in Scene Config. archmage keeps that list in
// `game.archmage.terrains` and only uses it to show terrain badges on a scene: it
// doesn't gate spells, so an extra entry is purely a display option
// (docs/DRUID-SPLIT.md).
//
// Reads DA_DATA.sceneTerrains: the terrain names of every "Terrain Caster: <name>"
// group in the class files, e.g. ["Cave, Dungeon, Underworld", "Desert, Wasteland"].
// A name archmage already lists (compared with its localized label) is skipped.

// Icons (Font Awesome) for the terrains we add; anything else gets the default.
const TERRAIN_ICONS = {
  "Desert, Wasteland": "fa-solid fa-sun",
  "Hellhole, Abyss": "fa-solid fa-fire",
  "Ocean, Island": "fa-solid fa-anchor",
  "Volcano": "fa-solid fa-volcano",
};

Hooks.once("ready", function () {
  const terrains = game.archmage?.terrains;
  if (!Array.isArray(terrains)) return;
  const existing = new Set(terrains.map((t) => game.i18n.localize(t.name).toLowerCase()));
  for (const name of DA_DATA.sceneTerrains ?? []) {
    if (existing.has(name.toLowerCase())) continue;
    // A camelCase id like archmage's own ("desertWasteland"); a name that is no
    // localization key is shown as it is.
    const id = name
      .toLowerCase()
      .replace(/[^a-z\d]+(.)/g, (_m, c) => c.toUpperCase())
      .replace(/[^a-z\d]/gi, "");
    terrains.push({ id, name, icon: TERRAIN_ICONS[name] ?? "fa-solid fa-mountain-sun" });
  }
});

// ---- vtt-scripts/granted-items.js ----
// Child entries (docs/DATA-FORMAT.md "granted"): adding a parent Item to a
// character also adds the children it lists, and removing the parent removes
// the children it created. Runs on every way an Item reaches an actor (Import
// Powers, drag from a compendium, "add item"), since it listens to
// createItem/deleteItem. Import Powers hiding the children is import-extras.js.
//
// Reads DA_DATA.flagScope (the key under which the exporter writes Item flags):
//   parent Item:  flags[scope].grants = [{ pack: "<this module's pack name>", id: "<Item _id in that pack>" }
//                                         | { packId: "<full pack id, any package>", name: "<Item name>" }]
//   granted copy: flags[scope].grantedBy = the parent's Item id on the actor,
//                 flags[scope].grantedByName = the parent's name at grant time
// A copy is tied to the one parent that created it: two parents granting the
// same power give two copies, and each goes with its own parent. Flags are read
// as plain properties, not getFlag(), which rejects scopes that aren't packages.

// The child's own text field that gets the "Created by <parent>" line.
const CREATED_BY_FIELD = "special";

const grantScope = DA_DATA.flagScope;

// A granted child that itself lists grants (item 1 grants item 2, item 2 grants
// item 3) is flattened: everything is created once and tied to the TOP parent
// (item 1), so removing item 1 removes all of it. The data is meant to list every
// child on the top parent; this is the fallback when it doesn't. Copies created
// here don't run this hook again (daGranted), and a `seen` set stops loops.
function grantChildData(child, parent) {
  const data = child.toObject();
  delete data._id;
  data.flags = foundry.utils.mergeObject(data.flags ?? {}, {
    [grantScope]: { grantedBy: parent.id, grantedByName: parent.name },
  });
  const field = (data.system[CREATED_BY_FIELD] ??= { value: "" });
  const line = `<p><em>Created by ${foundry.utils.escapeHTML(parent.name)}</em></p>`;
  field.value = field.value ? `${line}${field.value}` : line;
  return data;
}

async function collectGrants(refs, seen, found, missing, viaName) {
  for (const { pack: packName, id, packId, name } of refs) {
    // Own child: this module's pack + Item id. External: any package's full pack id + Item name.
    const pack = packId
      ? game.packs.get(packId)
      : game.packs.find((p) => p.metadata.packageType === "module" && p.metadata.name === packName);
    const childId = id ?? (await pack?.getIndex())?.find((e) => e.name === name)?._id;
    const child = childId ? await pack.getDocument(childId) : null;
    if (!child) {
      missing.push(packId ? `${packId}/${name}` : `${packName}/${id}`);
      continue;
    }
    const key = child.uuid ?? child.id;
    if (seen.has(key)) continue;
    seen.add(key);
    found.push(child);
    const nested = child.flags?.[grantScope]?.grants;
    if (nested?.length) {
      console.info(`Dark Alleys: ${child.name} (granted via ${viaName}) grants more; those are tied to the top parent too.`);
      await collectGrants(nested, seen, found, missing, viaName);
    }
  }
}

Hooks.on("createItem", async function (item, options, userId) {
  if (userId !== game.user.id || options?.daGranted) return;
  const actor = item.parent;
  if (actor?.documentName !== "Actor" || actor.type !== "character") return;
  const grants = item.flags?.[grantScope]?.grants;
  if (!grants?.length) return;

  const found = [];
  const missing = [];
  await collectGrants(grants, new Set(), found, missing, item.name);
  const children = found.map((child) => grantChildData(child, item));
  if (missing.length) {
    console.warn(`Dark Alleys: ${item.name} could not add ${missing.length} granted item(s): ${missing.join(", ")}`);
    ui.notifications.warn(`${item.name}: ${missing.length} granted power(s) could not be added.`);
  }
  if (children.length) await actor.createEmbeddedDocuments("Item", children, { daGranted: true });
});

Hooks.on("deleteItem", async function (item, options, userId) {
  if (userId !== game.user.id) return;
  const actor = item.parent;
  if (actor?.documentName !== "Actor" || !item.flags?.[grantScope]?.grants?.length) return;
  const ids = actor.items.filter((i) => i.flags?.[grantScope]?.grantedBy === item.id).map((i) => i.id);
  if (ids.length) await actor.deleteEmbeddedDocuments("Item", ids);
});

// ---- vtt-scripts/uses-init.js ----
// Uses that scale with an ability modifier (docs/DATA-FORMAT.md "Ability-mod-scaled
// use counts"): a power's max uses can be a formula ("[[@cha.mod]]"). archmage
// resolves it when the actor rests, but a power just added to a character keeps the
// placeholder count the export wrote (1), so it would start with the wrong number of
// uses. On creation, set the current uses to the resolved maximum. Only for powers
// that track that pool at all (uses not null), and only when the maximum is a
// formula: fixed counts are already right. `resolveMaxQuantity` is archmage 1.41+.
Hooks.on("createItem", async function (item, options, userId) {
  if (userId !== game.user.id) return;
  const actor = item.parent;
  if (actor?.documentName !== "Actor" || actor.type !== "character") return;
  if (typeof item.resolveMaxQuantity !== "function") return;
  const update = {};
  for (const [maxField, usesField] of [["maxQuantity", "quantity"], ["maxQuantitySecondary", "quantitySecondary"]]) {
    const raw = item.system?.[maxField]?.value;
    if (typeof raw !== "string" || !/\[\[|@/.test(raw)) continue;
    if (item.system?.[usesField]?.value == null) continue;
    const max = await item.resolveMaxQuantity(maxField);
    if (max != null) update[`system.${usesField}.value`] = max;
  }
  if (Object.keys(update).length) await item.update(update);
});
})();
